// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { GetAllMaOrdersSummariesData, GetAllMaOrdersSummariesResponses, CreateWeeklyOrderSummaryData, CreateWeeklyOrderSummaryResponses, CreateWeeklyOrderSummaryErrors, GetOrderSummaryFileLinkData, GetOrderSummaryFileLinkResponses, GetOrderSummaryFileLinkErrors, DoFrequencyAnalysisForProductVariantsData, DoFrequencyAnalysisForProductVariantsResponses, DoFrequencyAnalysisForProductVariantsErrors, DoFrequencyAnalysisForProductsData, DoFrequencyAnalysisForProductsResponses, DoFrequencyAnalysisForProductsErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get All Ma Orders Summaries
 */
export const getAllMaOrdersSummaries = <ThrowOnError extends boolean = false>(options?: Options<GetAllMaOrdersSummariesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAllMaOrdersSummariesResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/ma-apps/get-all-ma-orders-summaries',
        ...options
    });
};

/**
 * Create Weekly Order Summary
 */
export const createWeeklyOrderSummary = <ThrowOnError extends boolean = false>(options: Options<CreateWeeklyOrderSummaryData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CreateWeeklyOrderSummaryResponses, CreateWeeklyOrderSummaryErrors, ThrowOnError>({
        responseType: 'json',
        url: '/ma-apps/create-weekly-order-summary',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get Order Summary File Link
 */
export const getOrderSummaryFileLink = <ThrowOnError extends boolean = false>(options: Options<GetOrderSummaryFileLinkData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<GetOrderSummaryFileLinkResponses, GetOrderSummaryFileLinkErrors, ThrowOnError>({
        responseType: 'json',
        url: '/ma-apps/get-order-summary-file-link',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Do Frequency Analysis For Product Variants
 */
export const doFrequencyAnalysisForProductVariants = <ThrowOnError extends boolean = false>(options: Options<DoFrequencyAnalysisForProductVariantsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<DoFrequencyAnalysisForProductVariantsResponses, DoFrequencyAnalysisForProductVariantsErrors, ThrowOnError>({
        responseType: 'json',
        url: '/order-analysis/frequency-analysis-for-product-variants',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Do Frequency Analysis For Products
 */
export const doFrequencyAnalysisForProducts = <ThrowOnError extends boolean = false>(options: Options<DoFrequencyAnalysisForProductsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<DoFrequencyAnalysisForProductsResponses, DoFrequencyAnalysisForProductsErrors, ThrowOnError>({
        responseType: 'json',
        url: '/order-analysis/frequency-analysis-for-products',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};