// This file is auto-generated by @hey-api/openapi-ts

/**
 * AuroraMiscMaOrderSummary
 */
export type AuroraMiscMaOrderSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * From Date
     */
    from_date: string;
    /**
     * To Date
     */
    to_date: string;
    /**
     * Object Key
     */
    object_key: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * FrequencyAnalysisRequest
 */
export type FrequencyAnalysisRequest = {
    /**
     * Businessid
     */
    businessId: string;
    /**
     * Datasourceid
     */
    dataSourceId: string;
    /**
     * Minlift
     */
    minLift?: number;
    /**
     * Topn
     */
    topN?: number;
};

/**
 * GetWeeklyOrderFileLink
 */
export type GetWeeklyOrderFileLink = {
    /**
     * Summaryid
     */
    summaryId: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ShopifyWeeklyOrderSummaryBody
 */
export type ShopifyWeeklyOrderSummaryBody = {
    /**
     * Startdate
     */
    startDate: string;
    /**
     * Enddate
     */
    endDate: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetAllMaOrdersSummariesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ma-apps/get-all-ma-orders-summaries';
};

export type GetAllMaOrdersSummariesResponses = {
    /**
     * Response Get All Ma Orders Summaries
     * Successful Response
     */
    200: Array<AuroraMiscMaOrderSummary>;
};

export type GetAllMaOrdersSummariesResponse = GetAllMaOrdersSummariesResponses[keyof GetAllMaOrdersSummariesResponses];

export type CreateWeeklyOrderSummaryData = {
    body: ShopifyWeeklyOrderSummaryBody;
    path?: never;
    query?: never;
    url: '/ma-apps/create-weekly-order-summary';
};

export type CreateWeeklyOrderSummaryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateWeeklyOrderSummaryError = CreateWeeklyOrderSummaryErrors[keyof CreateWeeklyOrderSummaryErrors];

export type CreateWeeklyOrderSummaryResponses = {
    /**
     * Successful Response
     */
    200: AuroraMiscMaOrderSummary;
};

export type CreateWeeklyOrderSummaryResponse = CreateWeeklyOrderSummaryResponses[keyof CreateWeeklyOrderSummaryResponses];

export type GetOrderSummaryFileLinkData = {
    body: GetWeeklyOrderFileLink;
    path?: never;
    query?: never;
    url: '/ma-apps/get-order-summary-file-link';
};

export type GetOrderSummaryFileLinkErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetOrderSummaryFileLinkError = GetOrderSummaryFileLinkErrors[keyof GetOrderSummaryFileLinkErrors];

export type GetOrderSummaryFileLinkResponses = {
    /**
     * Response Get Order Summary File Link
     * Successful Response
     */
    200: string;
};

export type GetOrderSummaryFileLinkResponse = GetOrderSummaryFileLinkResponses[keyof GetOrderSummaryFileLinkResponses];

export type DoFrequencyAnalysisForProductVariantsData = {
    body: FrequencyAnalysisRequest;
    path?: never;
    query?: never;
    url: '/order-analysis/frequency-analysis-for-product-variants';
};

export type DoFrequencyAnalysisForProductVariantsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DoFrequencyAnalysisForProductVariantsError = DoFrequencyAnalysisForProductVariantsErrors[keyof DoFrequencyAnalysisForProductVariantsErrors];

export type DoFrequencyAnalysisForProductVariantsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DoFrequencyAnalysisForProductsData = {
    body: FrequencyAnalysisRequest;
    path?: never;
    query?: never;
    url: '/order-analysis/frequency-analysis-for-products';
};

export type DoFrequencyAnalysisForProductsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DoFrequencyAnalysisForProductsError = DoFrequencyAnalysisForProductsErrors[keyof DoFrequencyAnalysisForProductsErrors];

export type DoFrequencyAnalysisForProductsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseURL: 'http://127.0.0.1:8001' | (string & {});
};